#!/usr/bin/env python3

### BEGIN PATCH ###
# This fixes a problem caused by hyper trying to import deprecated APIs.
import collections.abc
#hyper needs the four following aliases to be done manually.
collections.Iterable = collections.abc.Iterable
collections.Mapping = collections.abc.Mapping
collections.MutableSet = collections.abc.MutableSet
collections.MutableMapping = collections.abc.MutableMapping
#Now import hyper
### END PATCH ###


import hyper

conn = hyper.HTTP20Connection("127.0.0.1:8080")
'''
, 
    port=None,
    secure=None, window_manager=None, enable_push=False, ssl_context=None, proxy_host=None, proxy_port=None, force_proto=None, **kwargs)
'''

print(conn)
print(dir(conn))


req = conn.request("https://127.0.0.1", "/foo")

print(req)
print(dir(req))


